version: 2

build:
  os: ubuntu-22.04
  tools:
    python: 3
  jobs:
    pre_build:
     - sphinx-apidoc -f -o docs/source/code_generated dcraft

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true