version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    pre_build:
     - sphinx-apidoc -f -o docs/source/code_generated dcraft

python:
  setup_py_install: true
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false